events {}

http {
    upstream pii_backend {
        least_conn;
        server server1:8081;
        server server2:8082;
        server server3:8083;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://pii_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}